version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">10"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
