version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: '@babel/*'
          update_type: 'semver:minor'
      - match:
          dependency_name: '@types/*'
          update_type: 'semver:minor'
      - match:
          dependency_name: '@typescript-eslint/*'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'eslint*'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'prettier'
          update_type: 'all'
      - match:
          dependency_name: 'sinon'
          update_type: 'semver:minor'
    ignored_updates:
      - match:
          dependency_name: "@types/node"
          version_requirement: ">10"
